
use spring_blog_db;

insert into posts (title, body, post_details_id) values ('Waiting For Armageddon', 'Persevering modular ability', 1);
insert into posts (title, body, post_details_id) values ('Crawlspace', 'Triple-buffered high-level middleware', 2);
insert into posts (title, body, post_details_id) values ('Or (a.k.a. My Treasure)', 'Cross-group secondary access',3);
insert into posts (title, body, post_details_id) values ('Hotel Very Welcome', 'Optional optimal matrices', 4);
insert into posts (title, body, post_details_id) values ('Italian for Beginners (Italiensk for begyndere)', 'Versatile modular definition', 5);
insert into posts (title, body, post_details_id) values ('Knucklehead', 'Focused zero defect projection', 6);
insert into posts (title, body, post_details_id) values ('Johnny Express', 'Sharable client-driven parallelism', 7);
insert into posts (title, body, post_details_id) values ('Unknown White Male', 'Total radical system engine', 8);
insert into posts (title, body, post_details_id) values ('Sugar Curtain, The (El telón de azúcar)', 'Robust bi-directional projection', 9);



insert into post_details (is_awesome, history_of_post,  topic_description) values (true, 'http://alexa.com/nibh/quisque/id/justo/sit.js?leo=id&maecenas=ligula&pulvinar=suspendisse&lobortis=ornare&est=consequat&phasellus=lectus&sit=in&amet=est&erat=risus&nulla=auctor&tempus=sed&vivamus=tristique&in=in&felis=tempus&eu=sit&sapien=amet&cursus=sem&vestibulum=fusce&proin=consequat&eu=nulla&mi=nisl&nulla=nunc&ac=nisl&enim=duis&in=bibendum&tempor=felis&turpis=sed&nec=interdum&euismod=venenatis&scelerisque=turpis&quam=enim&turpis=blandit&adipiscing=mi&lorem=in&vitae=porttitor&mattis=pede&nibh=justo&ligula=eu&nec=massa&sem=donec&duis=dapibus&aliquam=duis&convallis=at&nunc=velit&proin=eu&at=est&turpis=congue&a=elementum&pede=in&posuere=hac&nonummy=habitasse&integer=platea&non=dictumst&velit=morbi&donec=vestibulum&diam=velit&neque=id&vestibulum=pretium&eget=iaculis&vulputate=diam&ut=erat&ultrices=fermentum&vel=justo&augue=nec&vestibulum=condimentum&ante=neque&ipsum=sapien&primis=placerat&in=ante&faucibus=nulla&orci=justo&luctus=aliquam&et=quis&ultrices=turpis&posuere=eget&cubilia=elit&curae=sodales&donec=scelerisque&pharetra=mauris&magna=sit', 'reintermediate global supply-chains');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'https://youtu.be/sociis/natoque.js?morbi=adipiscing&vel=elit&lectus=proin&in=interdum&quam=mauris&fringilla=non&rhoncus=ligula&mauris=pellentesque&enim=ultrices&leo=phasellus&rhoncus=id&sed=sapien&vestibulum=in&sit=sapien&amet=iaculis&cursus=congue&id=vivamus', 'productize collaborative vortals');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'https://scribd.com/odio/justo.png?lobortis=congue&convallis=elementum&tortor=in&risus=hac&dapibus=habitasse&augue=platea&vel=dictumst&accumsan=morbi&tellus=vestibulum&nisi=velit&eu=id&orci=pretium&mauris=iaculis&lacinia=diam&sapien=erat&quis=fermentum&libero=justo&nullam=nec&sit=condimentum&amet=neque&turpis=sapien&elementum=placerat&ligula=ante&vehicula=nulla&consequat=justo&morbi=aliquam&a=quis&ipsum=turpis&integer=eget&a=elit&nibh=sodales&in=scelerisque&quis=mauris&justo=sit&maecenas=amet&rhoncus=eros&aliquam=suspendisse&lacus=accumsan&morbi=tortor&quis=quis&tortor=turpis&id=sed&nulla=ante&ultrices=vivamus&aliquet=tortor&maecenas=duis&leo=mattis&odio=egestas&condimentum=metus&id=aenean&luctus=fermentum&nec=donec&molestie=ut&sed=mauris&justo=eget&pellentesque=massa&viverra=tempor&pede=convallis&ac=nulla&diam=neque&cras=libero&pellentesque=convallis&volutpat=eget&dui=eleifend&maecenas=luctus&tristique=ultricies&est=eu&et=nibh&tempus=quisque&semper=id&est=justo&quam=sit&pharetra=amet&magna=sapien&ac=dignissim&consequat=vestibulum&metus=vestibulum&sapien=ante&ut=ipsum&nunc=primis&vestibulum=in&ante=faucibus&ipsum=orci&primis=luctus&in=et&faucibus=ultrices&orci=posuere&luctus=cubilia&et=curae&ultrices=nulla&posuere=dapibus&cubilia=dolor&curae=vel', 'utilize impactful paradigms');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'http://flavors.me/mauris.js?quis=non&orci=mauris&nullam=morbi&molestie=non&nibh=lectus&in=aliquam&lectus=sit&pellentesque=amet&at=diam&nulla=in&suspendisse=magna&potenti=bibendum&cras=imperdiet&in=nullam&purus=orci&eu=pede&magna=venenatis&vulputate=non&luctus=sodales&cum=sed&sociis=tincidunt&natoque=eu&penatibus=felis&et=fusce&magnis=posuere&dis=felis&parturient=sed&montes=lacus&nascetur=morbi&ridiculus=sem&mus=mauris&vivamus=laoreet&vestibulum=ut&sagittis=rhoncus&sapien=aliquet&cum=pulvinar&sociis=sed&natoque=nisl&penatibus=nunc&et=rhoncus&magnis=dui&dis=vel&parturient=sem&montes=sed&nascetur=sagittis&ridiculus=nam&mus=congue&etiam=risus&vel=semper&augue=porta', 'repurpose open-source content');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'http://netscape.com/sed.jpg?nisl=sed&aenean=augue&lectus=aliquam&pellentesque=erat&eget=volutpat&nunc=in&donec=congue&quis=etiam&orci=justo&eget=etiam&orci=pretium&vehicula=iaculis&condimentum=justo&curabitur=in&in=hac&libero=habitasse&ut=platea&massa=dictumst&volutpat=etiam&convallis=faucibus&morbi=cursus&odio=urna&odio=ut&elementum=tellus&eu=nulla&interdum=ut&eu=erat&tincidunt=id&in=mauris&leo=vulputate&maecenas=elementum&pulvinar=nullam&lobortis=varius&est=nulla&phasellus=facilisi&sit=cras&amet=non&erat=velit&nulla=nec&tempus=nisi&vivamus=vulputate&in=nonummy&felis=maecenas&eu=tincidunt&sapien=lacus&cursus=at&vestibulum=velit&proin=vivamus&eu=vel&mi=nulla&nulla=eget&ac=eros&enim=elementum&in=pellentesque&tempor=quisque&turpis=porta&nec=volutpat&euismod=erat&scelerisque=quisque&quam=erat&turpis=eros&adipiscing=viverra&lorem=eget&vitae=congue&mattis=eget&nibh=semper&ligula=rutrum&nec=nulla&sem=nunc&duis=purus&aliquam=phasellus&convallis=in&nunc=felis&proin=donec&at=semper&turpis=sapien&a=a&pede=libero&posuere=nam', 'reintermediate end-to-end models');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'http://simplemachines.org/eget/tincidunt/eget/tempus/vel.xml?aliquam=porttitor&non=lacus&mauris=at&morbi=turpis&non=donec&lectus=posuere&aliquam=metus&sit=vitae&amet=ipsum&diam=aliquam&in=non&magna=mauris&bibendum=morbi&imperdiet=non&nullam=lectus&orci=aliquam&pede=sit&venenatis=amet&non=diam', 'synergize scalable architectures');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'http://archive.org/rutrum/rutrum/neque.html?sem=vel&praesent=est&id=donec&massa=odio&id=justo&nisl=sollicitudin&venenatis=ut&lacinia=suscipit&aenean=a&sit=feugiat&amet=et&justo=eros&morbi=vestibulum&ut=ac&odio=est&cras=lacinia&mi=nisi&pede=venenatis&malesuada=tristique&in=fusce&imperdiet=congue&et=diam&commodo=id&vulputate=ornare&justo=imperdiet&in=sapien&blandit=urna&ultrices=pretium&enim=nisl&lorem=ut&ipsum=volutpat&dolor=sapien&sit=arcu&amet=sed&consectetuer=augue&adipiscing=aliquam&elit=erat&proin=volutpat&interdum=in&mauris=congue&non=etiam&ligula=justo&pellentesque=etiam&ultrices=pretium&phasellus=iaculis&id=justo&sapien=in&in=hac&sapien=habitasse&iaculis=platea&congue=dictumst&vivamus=etiam&metus=faucibus&arcu=cursus&adipiscing=urna&molestie=ut&hendrerit=tellus&at=nulla&vulputate=ut&vitae=erat&nisl=id&aenean=mauris&lectus=vulputate&pellentesque=elementum&eget=nullam&nunc=varius&donec=nulla&quis=facilisi&orci=cras&eget=non&orci=velit&vehicula=nec&condimentum=nisi&curabitur=vulputate&in=nonummy&libero=maecenas&ut=tincidunt&massa=lacus&volutpat=at', 'integrate viral synergies');
insert into post_details (is_awesome, history_of_post,  topic_description) values (true, 'http://huffingtonpost.com/metus/arcu.png?justo=interdum&maecenas=mauris&rhoncus=non&aliquam=ligula&lacus=pellentesque&morbi=ultrices&quis=phasellus&tortor=id&id=sapien&nulla=in&ultrices=sapien&aliquet=iaculis&maecenas=congue&leo=vivamus&odio=metus&condimentum=arcu&id=adipiscing&luctus=molestie&nec=hendrerit&molestie=at&sed=vulputate&justo=vitae&pellentesque=nisl&viverra=aenean&pede=lectus&ac=pellentesque&diam=eget&cras=nunc&pellentesque=donec&volutpat=quis&dui=orci&maecenas=eget&tristique=orci&est=vehicula&et=condimentum&tempus=curabitur&semper=in&est=libero&quam=ut&pharetra=massa&magna=volutpat&ac=convallis&consequat=morbi&metus=odio&sapien=odio&ut=elementum&nunc=eu&vestibulum=interdum&ante=eu&ipsum=tincidunt&primis=in&in=leo&faucibus=maecenas&orci=pulvinar&luctus=lobortis&et=est&ultrices=phasellus&posuere=sit&cubilia=amet&curae=erat&mauris=nulla&viverra=tempus&diam=vivamus&vitae=in&quam=felis&suspendisse=eu&potenti=sapien&nullam=cursus&porttitor=vestibulum&lacus=proin&at=eu&turpis=mi&donec=nulla&posuere=ac&metus=enim&vitae=in&ipsum=tempor&aliquam=turpis&non=nec&mauris=euismod&morbi=scelerisque&non=quam&lectus=turpis&aliquam=adipiscing&sit=lorem&amet=vitae&diam=mattis&in=nibh&magna=ligula&bibendum=nec&imperdiet=sem&nullam=duis&orci=aliquam&pede=convallis&venenatis=nunc&non=proin', 'envisioneer sexy relationships');
insert into post_details (is_awesome, history_of_post,  topic_description) values (false, 'http://devhub.com/quis/tortor/id/nulla.html?vulputate=luctus&vitae=et&nisl=ultrices&aenean=posuere&lectus=cubilia&pellentesque=curae&eget=duis&nunc=faucibus&donec=accumsan&quis=odio&orci=curabitur&eget=convallis&orci=duis&vehicula=consequat&condimentum=dui', 'engage innovative deliverables');
insert into post_details (is_awesome, history_of_post,  topic_description) values (true, 'http://blog.com/id/nisl/venenatis/lacinia/aenean.aspx?velit=faucibus&eu=accumsan&est=odio&congue=curabitur&elementum=convallis&in=duis&hac=consequat&habitasse=dui&platea=nec&dictumst=nisi&morbi=volutpat&vestibulum=eleifend&velit=donec&id=ut&pretium=dolor&iaculis=morbi&diam=vel&erat=lectus&fermentum=in&justo=quam&nec=fringilla&condimentum=rhoncus&neque=mauris&sapien=enim&placerat=leo&ante=rhoncus&nulla=sed&justo=vestibulum&aliquam=sit&quis=amet&turpis=cursus&eget=id&elit=turpis&sodales=integer&scelerisque=aliquet&mauris=massa&sit=id&amet=lobortis&eros=convallis&suspendisse=tortor&accumsan=risus&tortor=dapibus&quis=augue&turpis=vel&sed=accumsan&ante=tellus&vivamus=nisi&tortor=eu&duis=orci&mattis=mauris&egestas=lacinia&metus=sapien&aenean=quis&fermentum=libero&donec=nullam&ut=sit&mauris=amet&eget=turpis&massa=elementum&tempor=ligula&convallis=vehicula&nulla=consequat&neque=morbi&libero=a&convallis=ipsum&eget=integer&eleifend=a&luctus=nibh', 'benchmark ubiquitous portals');